spring:
  application:
    name: discovery-server

server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}