@startuml
!include c4/C4_Context.puml

title WarmHouse Context Diagram

top to bottom direction

Person(user, "User", "A user of the WarmHouse system")
System(WarmHouseSystem, "WarmHouse System", "Sensor control system, temperature monitoring")

System_Ext(HeatingSystem, "Heating system")

Rel(user,WarmHouseSystem,"Uses the system")
Rel(WarmHouseSystem,HeatingSystem,"Turn the heating on/off")
Rel(WarmHouseSystem,HeatingSystem,"Receive temperature data from sensors")
Rel(user,WarmHouseSystem,"View the current temperature in your home via a web interface")
@enduml